# Generated by Django 4.0.4 on 2022-07-02 02:56

from django.db import migrations, models
import dronesapp.validators
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('serial_number', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('model', models.CharField(choices=[('lightweight', 'Light weight'), ('middleweight', 'Middle weight'), ('cruiserweight', 'Cruiser weight'), ('heavyweight', 'Heavy weight')], max_length=50, verbose_name='model')),
                ('weight_limit_gr', models.FloatField(validators=[dronesapp.validators.validate_weight_limit], verbose_name='Weight Limit (gr)')),
                ('battery_capacity', models.IntegerField(validators=[dronesapp.validators.validate_battery_capacity], verbose_name='Battery Capacity')),
                ('state', models.CharField(choices=[('idle', 'Idle'), ('loading', 'loading'), ('loaded', 'loaded'), ('delivering', 'delivering'), ('delivered', 'delivered'), ('returning', 'returning')], max_length=50, verbose_name='state')),
                ('active', models.BooleanField(default=True, verbose_name='active')),
            ],
            options={
                'verbose_name': 'drone',
                'verbose_name_plural': 'drones',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(max_length=255, validators=[dronesapp.validators.validate_med_name])),
                ('weight_gr', models.FloatField(validators=[dronesapp.validators.validate_weight], verbose_name='Weight (gr)')),
                ('code', models.CharField(max_length=255, validators=[dronesapp.validators.validate_med_code])),
                ('image', models.ImageField(upload_to='medication/', validators=[dronesapp.validators.validate_image_size], verbose_name='image')),
            ],
            options={
                'verbose_name': 'medication',
                'verbose_name_plural': 'medications',
                'ordering': ('-created_at',),
            },
        ),
    ]
