# Generated by Django 4.0.4 on 2022-07-06 02:16

from django.db import migrations, models
import dronesapp.validators


class Migration(migrations.Migration):

    dependencies = [
        ('dronesapp', '0004_dronepackage_batterylogs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='image',
            field=models.ImageField(null=True, upload_to='medication/', validators=[dronesapp.validators.validate_image_size], verbose_name='image'),
        ),
    ]
