# Generated by Django 4.0.4 on 2022-07-06 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dronesapp', '0005_alter_medication_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='dronepackage',
            name='delivered',
            field=models.BooleanField(default=False, verbose_name='Delivered'),
        ),
    ]
